config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :lessons, only: %i(show update)
  resources :words, only: %i(index)
  devise_for :users
  resources :users, only: %i(show index) do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  validates :content, presence: true

  scope :alls, ->user_id{}
  scope :learned, ->user_id{where "id IN (SELECT word_id FROM answers WHERE
    correct = '1' AND id IN (SELECT answer_id FROM results WHERE lesson_id IN (SELECT id FROM
      lessons WHERE user_id = #{user_id})))"}
  scope :not_learned, ->user_id{where "id NOT IN (SELECT word_id FROM answers WHERE
    correct = '1' and id IN (SELECT answer_id FROM results WHERE lesson_id IN (SELECT id FROM
      lessons WHERE user_id = #{user_id})))"}
  scope :order_date_desc, ->{order created_at: :desc}
  validate :must_be_a_answer_correct, on: [:create, :update]

  scope :order_by_name, ->{order :content}

  private
  def must_be_a_answer_correct
    unless self.answers.select{|answer| answer.correct}.size == Settings.a_answer_correct
      errors.add " ", I18n.t(:must_have_correct_answer)
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :load_word, only: %i(edit update destroy)
  before_action :select_category, except: %i(index destroy)

  def index
    @q = Word.search(params[:q])
    @words = @q.result.order_date_desc.page(params[:page]).per Settings.word_per_page
  end

  def new
    @word = Word.new
  end

  def edit; end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] =  t :successfully_created_word
      redirect_to admin_words_path
    else

      flash[:danger] = @word.errors.full_messages.join(", ")
      render :new
    end
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t :successfully_updated_word
      redirect_to admin_words_path
    else
      flash[:danger] = @word.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t :successfully_destroy_word
    else
      flash[:danger] = t :fail_destroy_word
    end
    redirect_to admin_words_path
  end

  private

  def select_category
    @category = Category.all
  end

  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :content, :correct, :_destroy]
  end

  def load_word
    @word = Word.find_by id: params[:id]
    return if @word
    flash[:error] = t :word_not_found
    redirect_to admin_root_path
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @categories = Category.select(:id, :name)
    if !params[:category_id].nil? && params[:category_id].empty?
      @words = Word.send params[:option], current_user.id
    elsif category = @categories.find_by(id: params[:category_id])
      @words = category.words.send params[:option], current_user.id
    else
      @words = Word.all
    end
    @words = @words.order_by_name.includes(:category, :answers).page(params[:page]).per Settings.word_per_page
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def correct_answer word
    word.answers.correct_answer.first.content
  end

  def count_correct_answer word
    word.answers.correct_answer.size
  end

end

app/views/admin/words/_answer_fields.html.erb
<p class="fields">
    <%= f.text_field :content, id: "answer-form" %>
    <%= f.label :correct %>
    <%= f.check_box :correct, id: "check_box" %>
    <%= f.hidden_field :_destroy, class: "destroy" %>
    <%= link_to t(:remove), "#", class: "btn-remove-answer" %>
</p>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control" %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @category, :id, :name, {},
    {class: "form-control"} %>

  <%= f.fields_for :answers do |builder| %>
    <%= render "answer_fields", f: builder %>
  <% end %>

  <p><%= link_to_add_fields (t :add_answer), f, :answers %></p>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/words/_word.html.erb
<% @words.each_with_index do |word, index| %>
  <tr>
    <td><%= create_index params[:page], index, Settings.word_per_page %></td>
    <td><%= word.content %></td>
    <td><%= word.category.name %></td>
    <td>
      <%= link_to t(:edit), edit_admin_word_path(word), class: "btn btn-primary" %>
      <%= link_to t(:delete), admin_word_path(word), class: "btn btn-danger",
        method: :delete, data: { confirm: t(:sure)}  %>
    </td>
  </tr>
<% end %>

app/views/admin/words/edit.html.erb
<%= provide :button_text, t(:save_changes) %>
<h1><%= t :update_word_info %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h1><%= t :all_word %></h1>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <%= search_form_for [:admin, @q] do |f| %>
        <%= f.text_field :content_cont, placeholder: t(:search_by_content),
          class: "form-control" %>
        <%= f.submit t(:search), class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-8 col-md-offset-1">
    <br>
    <%= link_to t(:create_word), new_admin_word_url, class: "btn btn-primary" %>
      <div class="card-body">
        <br>
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable">
            <thead>
              <tr>
                <th><%= t :index %></th>
                <th><%= t :content %></th>
                <th><%= t :category %></th>
                <th><%= t :action %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "word" %>
            </tbody>
          </table>
        </div>
        <div class="text-center">
          <%= paginate @words %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<%= provide :button_text, t(:create_word) %>
<h1><%= t :add_word %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= render "form" %>
  </div>
</div>