config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :lessons, only: %i(show update)
  resources :words, only: %i(index)
  devise_for :users
  resources :users, only: %i(show index) do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/views/shared/_left_side_bar.html.erb
<div class="col-lg-2">
  <h1 class="my-4"><%= t :data %></h1>
  <div class="list-group">
    <ul class="nav nav-sidebar">
      <li><%= link_to t(:user), admin_users_path %></li>
      <li><%= link_to t(:categories), admin_categories_path %></li>
      <li><%= link_to t(:word), admin_words_path %></li>
  </ul>
  </div>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type%> ">
    <button type = "button" class ="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t :following %>
  </a>
  <a href="<%= followers_user_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t :followers %>
  </a>
  <br>
</div>