config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :lessons, only: %i(show update)
  resources :words, only: %i(index)
  devise_for :users
  resources :users, only: %i(show index) do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:admin, :user]

  has_many :lessons, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  scope :order_date_desc, ->{order created_at: :desc}
  scope :order_by_email, ->{order :email}

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :load_user, only: %i(edit update destroy )

  def index
    @q = User.search params[:q]
    @users = @q.result.order_by_email.page(params[:page]).
      per Settings.user_per_page
  end

  def edit; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t :create_user_success
      redirect_to admin_users_path
    else
      flash[:danger] = t :create_user_fail
      render :new
    end
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t :updated_user
      redirect_to admin_users_path
    else
      flash[:danger] = t :update_user_fail
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t :deleted_user
    else
      flash[:danger] = t :delete_user_fail
    end
    redirect_to admin_users_path
  end


  private

  def user_params
    params.require(:user).permit :name, :email, :password
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t :user_not_found
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(show following followers)

  def index
    @users = User.order_date_desc.page(params[:page]).per Settings.user_per_page
  end

  def show
    @unfollow_user = current_user.active_relationships.find_by followed_id: @user.id
    @follow_user = current_user.active_relationships.build
  end

  def following
    @title = t :following
    @users = @user.following.page(params[:page])
    render "show_follow"
  end

  def followers
    @title = t :followers
    @users = @user.followers.page(params[:page])
    render "show_follow"
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:warning] = t :not_found
    redirect_to user_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.ava_size
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def current_user? user
    user == current_user
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :mail %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_user.html.erb
<% @users.each_with_index do |user, index| %>
  <tr>
    <td><%= create_index params[:page], index, Settings.user_per_page %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <%= link_to t(:edit), edit_admin_user_path(user), class: "btn btn-primary" %>
      <%= link_to t(:delete), admin_user_path(user), class: "btn btn-danger",
        method: :delete, data: { confirm: t(:sure)}  %>
    </td>
  </tr>
<% end %>

app/views/admin/users/edit.html.erb
<%= provide :button_text, t(:save_changes) %>
<h1><%= t :update_user_info %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= render "form" %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="card mb-3">
  <div class="card-header">
    <h1><%= t :all_users %></h1>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <%= search_form_for [:admin, @q] do |f| %>
        <%= f.text_field :name_or_email_cont, placeholder: t(:search_by_name_or_email),class: "form-control" %>
        <%= f.submit t(:search), class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-8 col-md-offset-1">
    <br>
    <%= link_to t(:create_user), new_admin_user_url, class: "btn btn-primary" %>
      <div class="card-body">
        <br>
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable">
            <thead>
              <tr>
                <th><%= t :index %></th>
                <th><%= t :name %></th>
                <th><%= t :email %></th>
                <th><%= t :action %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "user" %>
            </tbody>
          </table>
        </div>
        <div class="text-center">
          <%= paginate @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= provide :button_text, t(:create_user) %>
<h1><%= t :add_user %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= render "form" %>
  </div>
</div>