config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :categories, only: %i(index show) do
    resources :lessons, only: %i(create)
  end
  resources :lessons, only: %i(show update)
  resources :words, only: %i(index)
  devise_for :users
  resources :users, only: %i(show index) do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if user_signed_in? %>
    <p>
      <%= t :last_sign_in %>
      <%= l current_user.last_sign_in_at, format: :date_month_year %>
    </p>
    <p><%= t :current_ip %> <%= current_user.current_sign_in_ip %></p>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "E-Learning System", root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
          <% if current_user.admin? %>
            <li><%= link_to t(:admin), admin_root_path %></li>
          <% else %>
            <li><%= link_to t(:home), root_path %></li>
            <li><%= link_to t(:categories), categories_path %></li>
            <li><%= link_to t(:word_list), words_path %></li>
            <li><%= link_to t(:all_users), users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t :account %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:profile), user_path(current_user) %></li>
              <li><%= link_to t(:settings), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(:log_out), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
        <% else %>
            <li><%= link_to t(:home), root_path %></li>
            <li><%= link_to t(:log_in), new_user_session_path %></li>
            <li><%= link_to t(:sign_up), new_user_registration_path %></li>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
                            "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "shared/messages" %>
      <% if user_signed_in? && current_user.admin? %>
        <%= render "shared/left_side_bar" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>